version: '3'
services:
  # Backend Service
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: shopping_app
    depends_on:
      - db
    volumes:
      - ./backend:/app
    networks:
      - app-network

  # Frontend Service
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - app-network

  # Database Service (PostgreSQL)
  db:
    image: postgres
    environment:
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: shopping_app
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:

volumes:
  pgdata:
